name: Publish annobel to PyPI

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: pip

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine flake8

      - name: Lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=12 --max-line-length=120 --statistics

      - name: Build sdist & wheel
        run: python -m build

      - name: Check artifacts
        run: twine check dist/*

      - name: Upload artifacts (record)
        uses: actions/upload-artifact@v4
        with:
          name: annobel-dist
          path: dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.annobel }}
          skip-existing: false
