name: Publish annobel distributions

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Automatic + manual YOLO-format bounding box annotation tool"
        required: true
        default: testpypi
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.9"
            cache: pip

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine flake8

      - name: Lint (critical)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=12 --max-line-length=120 --statistics

      - name: Verify version consistency
        run: |
          PY_V_PYPROJ=$(grep -E '^version *=' pyproject.toml | head -1 | sed 's/version *= *"//; s/"//')
          PY_V_SETUP=$(grep -E 'version="' setup.py | head -1 | sed 's/.*version="//; s/".*//')
          if [ "$PY_V_PYPROJ" != "$PY_V_SETUP" ]; then
            echo "Version mismatch: pyproject=$PY_V_PYPROJ setup=$PY_V_SETUP"; exit 1; fi
          echo "Version: $PY_V_PYPROJ"

      - name: Build sdist + wheel
        run: python -m build

      - name: Check artifacts
        run: |
          ls -l dist
          twine check dist/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: annobel-dist
          path: dist/*

      - name: Publish to TestPyPI (manual dispatch)
        if: github.event_name == 'workflow_dispatch' && inputs.target == 'testpypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.annobel }}
          skip-existing: true
          user: __token__

      - name: Publish to PyPI (tag or manual)
        if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || (github.event_name == 'workflow_dispatch' && inputs.target == 'pypi')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.annobel }}
          user: __token__
          skip-existing: false
